[project]
name = "haylin"
version = "0.0.1"
authors = [
  { name="Haylin Diaz", email="hdiaz@g.harvard.edu" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://github.com/h04032013/package-tutorial"
Issues = "https://github.com/h04032013/package-tutorial/issues"